# Generated by Django 6.0.4 on 2026-04-17 17:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=500)),
                ('criado_em', models.DateField(auto_now=True)),
                ('atualizado_em', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=1000)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, max_length=10)),
                ('quantidade_estoque', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('imagem', models.URLField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categoria')),
            ],
        ),
    ]
